Repository Air-Clean/airclean-reactjs, pull requests merged in 2024-07, with the labels that each got.

#3 [feature] 문의 창 중간
  package-lock.json
  package.json
  src/apis/MemberAPICalls.js
  src/components/header/AdminHeader.js
  src/components/header/ClientHeader.js
  src/index.js
  src/layouts/Layout.js
  src/pages/login/Login.js
  src/pages/login/login.module.css
Labels: feature

#4 [feature] 문의 창 중간 커밋
  src/apis/MemberAPICalls.js
  src/components/header/AdminHeader.js
  src/components/header/ClientHeader.js
  src/components/header/Header.module.css
  src/modules/AskModule.js
  src/modules/MemberModule.js
  src/modules/index.js
  src/pages/login/AskWindow.js
  src/pages/login/Login.js
Labels: feature

#5 [FEATURE] 헤더
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/header/AdminHeader.js
  src/layouts/Layout.js
  src/pages/admin/human_resource/BioCard.js
  src/pages/admin/human_resource/BranchResource.js
  src/pages/admin/human_resource/DriverResource.js
  src/pages/admin/human_resource/EmployeeResource.js
  src/pages/admin/human_resource/HumanResource.css
  src/pages/admin/human_resource/TempResource.js
  src/pages/login/AskWindow.js
  src/styles/index.css
Labels: feature

#12 [FEATURE]Car3 css 구현
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/apis/HRAPICalls.js
  src/apis/MemberAPICalls.js
  src/components/header/AdminHeader.js
  src/components/header/ClientHeader.js
  src/components/header/Header.module.css
  src/components/paging/Paging.js
  src/components/paging/Paging.module.css
  src/index.js
  src/layouts/Layout.js
  src/modules/AskModule.js
  src/modules/HRModule.js
  src/modules/MemberModule.js
  src/modules/index.js
  src/pages/admin/human_resource/BioCard.js
  src/pages/admin/human_resource/BranchResource.js
  src/pages/admin/human_resource/DriverResource.js
  src/pages/admin/human_resource/EmployeeResource.js
  src/pages/admin/human_resource/HumanResource.css
  src/pages/admin/human_resource/Searchbar.js
  src/pages/admin/human_resource/TempResource.js
  src/pages/admin/report/newReportsMenu/NewReports.css
  src/pages/admin/report/newReportsMenu/NewReports.js
  src/pages/admin/report/reportsMenu/BranchSales.js
  src/pages/admin/report/reportsMenu/Reports.css
  src/pages/car/Car.css
  src/pages/car/Car.js
  src/pages/login/AskWindow.js
  src/pages/login/Login.js
  src/pages/login/login.module.css
  src/styles/index.css
Labels: feature

#24 [FEATURE] human resource
  src/apis/HRAPICalls.js
  src/pages/admin/human_resource/BioCard.js
  src/pages/admin/human_resource/EmployeeResource.js
  src/pages/admin/human_resource/HumanResource.css
Labels: feature

#26 보고서관리 - 보고서작성 - 보고서작성모달
  src/pages/admin/report/newReportsMenu/NewReports.css
  src/pages/admin/report/newReportsMenu/NewReports.js
  src/pages/admin/report/newReportsMenu/ReportsModal.js
  src/pages/admin/report/newReportsMenu/ReportsModal.module.css
  src/pages/admin/report/reportsMenu/BranchSales.js
Labels: feature

#34 지출보고서 - 상세보기
  src/App.js
  src/apis/ReportAPICalls.js
  src/modules/ReportsModule.js
  src/modules/index.js
  src/pages/admin/report/newReportsMenu/NewReports.js
  src/pages/admin/report/newReportsMenu/ReportsModal.module.css
  src/pages/admin/report/reportsMenu/BranchSales.js
  src/pages/admin/report/reportsMenu/BranchSalesDetail.css
  src/pages/admin/report/reportsMenu/BranchSalesDetail.js
Labels: feature

#49 [Feature] 재고내역 조회
  src/apis/StockAPICalls.js
  src/modules/StockModule.js
  src/modules/index.js
  src/pages/admin/stock/StockApplication.js
  src/pages/admin/stock/StockHistory.js
Labels: feature

#50 보고서관리 - 차량수리보고서 상세조회
  src/App.js
  src/apis/ReportAPICalls.js
  src/modules/ReportsModule.js
  src/modules/index.js
  src/pages/admin/report/reportsMenu/AdminBranchSales.js
  src/pages/admin/report/reportsMenu/BranchSales.js
  src/pages/admin/report/reportsMenu/BranchSalesDetail.js
  src/pages/admin/report/reportsMenu/VehicleRepairDetail.js
Labels: feature

#53 [FEATURE] 보고서관리- 보고서조회 - 시설물수리보고서 세부조회
  src/App.js
  src/apis/ReportAPICalls.js
  src/modules/ReportsModule.js
  src/modules/index.js
  src/pages/admin/report/reportsMenu/BranchSales.js
  src/pages/admin/report/reportsMenu/RepairDetail.js
  src/pages/client/locationReports/locationNewReportsMenu/LocationNewReports.css
Labels: feature

#59 [FEATURE]보고서 양식 - 지점장페이지 보고서 양식 모달 추가
  src/pages/client/locationReports/locationNewReportsMenu/BranchSalesModal.js
  src/pages/client/locationReports/locationNewReportsMenu/ExpenseModal.js
  src/pages/client/locationReports/locationNewReportsMenu/LocationNewReports.css
  src/pages/client/locationReports/locationNewReportsMenu/LocationNewReports.js
  src/pages/client/locationReports/locationNewReportsMenu/Modal.css
  src/pages/client/locationReports/locationNewReportsMenu/RepairModal.js
Labels: feature

#63 [FEATURE]보고서관리 - 보고서조회 - 매출보고서 승인/반려
  src/pages/admin/report/reportsMenu/BranchSalesDetail.js
  src/pages/admin/report/reportsMenu/ExpenseDetail.js
  src/pages/client/locationReports/locationNewReportsMenu/LocationNewReports.css
Labels: feature

#64 [Feature]stock history
  src/App.js
  src/pages/admin/human_resource/driver/DriverResource.js
  src/pages/admin/stock/BranchOrderHistory.js
  src/pages/admin/stock/StockApplication.css
  src/pages/admin/stock/StockApplication.js
  src/pages/admin/stock/StockHistory.js
  src/pages/admin/stock/StockHistoryLayout.css
  src/pages/admin/stock/StockHistoryLayout.js
  src/pages/admin/stock/StockHistoryNavBar.css
  src/pages/admin/stock/StockHistoryNavBar.js
Labels: feature

#70 [CSS] mainpage css 완성
  .gitignore
  package-lock.json
  package.json
  src/pages/admin/human_resource/Temp/AccordionComponent.js
  src/pages/admin/human_resource/Temp/Garbage.js
  src/pages/admin/human_resource/Temp/TempResource.js
  src/pages/admin/main_page/AdminMenu1.css
  src/pages/admin/main_page/ExBarGraph.js
  src/pages/admin/main_page/ExBarGraphCss.css
  src/pages/admin/main_page/ExPieGraph.js
  src/pages/admin/main_page/ExPieGraphCss.css
  src/pages/admin/main_page/ExpenditureBox.js
  src/pages/admin/main_page/ExpenditureBoxCss.css
  src/pages/admin/main_page/MainHeader.js
  src/pages/admin/main_page/MainHeaderCss.css
  src/pages/admin/main_page/MainPage.js
  src/pages/admin/main_page/RevenueBox.js
  src/pages/admin/main_page/RevenueBoxCSS.css
  src/pages/admin/main_page/RevenueGraph.js
  src/pages/admin/main_page/RevenuePie.js
  src/pages/admin/main_page/TopBox.js
  src/pages/admin/main_page/TopBoxCss.css
  src/pages/admin/main_page/UtilityBar.js
  src/pages/admin/main_page/UtilityBox.js
  src/pages/admin/main_page/UtilityBoxCss.css
  src/pages/admin/main_page/UtilityTab.js
  src/pages/admin/main_page/UtilityTabCss.css
Labels: 🎨Html&css

#77 [FEATURE]보고서관리- 승인/반려
  src/apis/ReportAPICalls.js
  src/modules/ReportsModule.js
  src/modules/index.js
  src/pages/admin/report/newReportsMenu/NewReports.js
  src/pages/admin/report/newReportsMenu/ReportsModal.js
  src/pages/admin/report/newReportsMenu/ReportsModal.module.css
  src/pages/admin/report/reportsMenu/BranchSales.js
  src/pages/admin/report/reportsMenu/ExpenseDetail.js
  src/pages/admin/report/reportsMenu/RepairDetail.js
  src/pages/admin/report/reportsMenu/VehicleRepairDetail.js
Labels: ✨Feature, 📫API, 🎨Html&css

#89 [FEATURE] 보고서작성- 차량수리보고서 등록
  src/pages/admin/report/reportsMenu/VehicleRepairDetail.js
Labels: ✨Feature, 📫API, 🎨Html&css, :page_with_curl: DB

#96 [featrue] branch 지점 관리 api 생성
  src/apis/CallBranchMapApi.js
  src/apis/MemberAPICalls.js
  src/components/branch/Action.js
  src/modules/BranchModule.js
  src/pages/admin/branch/Branch.js
  src/pages/admin/branch/store.js
Labels: 📫API

#101 [FEATURE] 지점장페이지/ 보고서양식 - 지출보고서 등록
  src/apis/ReportAPICalls.js
  src/modules/ReportsModule.js
  src/modules/index.js
  src/pages/client/locationReports/locationNewReportsMenu/BranchSalesModal.js
  src/pages/client/locationReports/locationNewReportsMenu/ExpenseModal.js
  src/pages/client/locationReports/locationNewReportsMenu/LocationNewReports.js
Labels: ✨Feature, 📫API, 🎨Html&css, :page_with_curl: DB

#102 [CSS]물류시스템
  src/apis/CarAPICalls.js
  src/apis/DriverCarAPICalls.js
  src/pages/admin/car/Car.js
  src/pages/admin/car/Car.module.css
Labels: css

#106 [FEATURE] 지점장페이지/ 보고서양식 - 시설물수리 보고서 모달창 구현
  src/apis/ReportAPICalls.js
  src/modules/ReportsModule.js
  src/modules/index.js
  src/pages/admin/report/reportsMenu/RepairDetail.js
  src/pages/client/locationReports/locationNewReportsMenu/LocationNewReports.js
  src/pages/client/locationReports/locationNewReportsMenu/RepairModal.js
Labels: ✨Feature, 📫API, 🎨Html&css, :page_with_curl: DB

#108 [feature] branch 등록 삭제 css 변경
  src/apis/CallBranchInfoApi.js
  src/components/branch/BranchList.js
  src/components/branch/BranchModal.js
  src/components/branch/Branchinformation.js
  src/components/branch/BranchinformationCss.css
  src/components/branch/Map.css
  src/components/branch/Map.js
  src/modules/BranchModule.js
  src/modules/index.js
  src/pages/admin/branch/Branch.js
  src/pages/admin/branch/store.js
  src/pages/admin/main_page/RevenueBox.js
Labels: ✨Feature
